package com.finlytics.dto;

import lombok.Data;

@Data
public class UserReqDTO {

    private String username;
    private String password;
    private String email;
    private String role;
    private String phoneNumber;

    // Constructors, getters, and setters can be generated by Lombok
}
